# Generated by Django 4.2.4 on 2023-09-26 17:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('party_limit', models.IntegerField(blank=True, default=3)),
                ('party_now', models.IntegerField(blank=True, default=0, null=True)),
                ('locate_start', models.CharField(blank=True, max_length=100)),
                ('locate_end', models.CharField(blank=True, max_length=100)),
                ('plan_at', models.DateTimeField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='json')),
                ('is_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('isEssential', models.BooleanField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('picture', models.TextField(blank=True)),
                ('blocked_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UsersDriver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mota.users')),
                ('car_no', models.CharField(blank=True, max_length=20)),
                ('car_type', models.CharField(blank=True, max_length=20)),
                ('car_limit', models.IntegerField(blank=True, default=3)),
                ('car_pictures', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('license_path', models.TextField()),
                ('license_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'users_driver',
            },
        ),
        migrations.CreateModel(
            name='UsersRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.users')),
            ],
            options={
                'db_table': 'users_rooms',
            },
        ),
        migrations.CreateModel(
            name='UsersReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.rooms')),
                ('userfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfrom', to='mota.users')),
                ('userto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userto', to='mota.users')),
            ],
            options={
                'db_table': 'users_reviews',
            },
        ),
        migrations.CreateModel(
            name='UsersApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prove', models.CharField(default='wait', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.users')),
            ],
            options={
                'db_table': 'users_approved',
            },
        ),
        migrations.CreateModel(
            name='UidDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mota.users')),
                ('firebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uid_dict',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.users'),
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField(blank=True, default=dict, verbose_name='json')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('read_at', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.users')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
    ]
