# Generated by Django 4.2.4 on 2023-10-11 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('chat_name', models.CharField(blank=True, max_length=100)),
                ('read_until', models.IntegerField(blank=True, default=0)),
                ('load_since', models.IntegerField(blank=True, default=0)),
                ('load_until', models.IntegerField(blank=True, default=None, null=True)),
                ('will_notify', models.BooleanField(blank=True, default=True)),
                ('last_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota.users')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
    ]
