# Generated by Django 4.2.4 on 2023-10-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mota', '0002_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='last_upload',
        ),
    ]
